# Generated by Django 6.1.1 on 2026-09-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
