# Generated by Django 6.1.1 on 2026-09-09 15:29

from django.db import migrations


def populate_nicknames(apps, schema_editor):
    Members = apps.get_model("members", "Members")

    for member in Members.objects.all():
        member.nickname = member.name
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_course_passport_alter_members_options_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_nicknames),
    ]
