# Generated by Django 6.1.1 on 2026-09-09 15:39

from django.db import migrations


def fill_nicknames(apps, schema_editor):
    Members = apps.get_model("members", "Members")

    for member in Members.objects.all():
        member.nickname = member.name
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_populate_nicknames"),
    ]

    operations = [
        migrations.RunPython(fill_nicknames),
    ]
