# Generated by Django 6.1.1 on 2026-09-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_article_video_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumMembers",
            fields=[],
            options={
                "ordering": ["-age"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.members",),
        ),
    ]
